FROM postgres:latest

RUN echo 'host all all all md5' >> /var/lib/postgresql/data/pg_hba.conf
RUN sed -i "s/#port/port/g" /var/lib/postgresql/data/postgresql.conf

EXPOSE 5432

ENTRYPOINT ["docker-entrypoint.sh", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]
CMD ["postgres"]
