FROM ubuntu:22.04

RUN echo "deb http://apt.postgresql.org/pub/repos/apt/jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list
ADD https://www.postgresql.org/media/keys/ACCC4CF8.asc .
RUN apt-key add - ACCC4CF8.asc
RUN apt-key adv --fetch-keys https://www.postgresql.org/media/keys/ACCC4CF8.asc
RUN apt update && apt upgrade
RUN apt install postgresql-15
RUN echo "host all all all md5" >> /etc/postgresql/15/main/pg_hba.conf
RUN sed -i "s/#port/port/g" /etc/postgresql/15/main/postgresql.conf

RUN /etc/init.d/postgresql start

# Expose the PostgreSQL port
EXPOSE 5432

# Add VOLUMEs to allow backup of databases
VOLUME ["/var/lib/postgresql/data"]

# Set the default command to run when starting the container
CMD ["/usr/lib/postgresql/15/bin/postgres", "-D", "/var/lib/postgresql/data", "-c", "config_file=/etc/postgresql/15/main/postgresql.conf"]

----------------
FROM ubuntu:22.04

#RUN echo "deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list
#RUN apt install wget
#RUN wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN apt update -y
RUN apt upgrade -y
RUN apt install postgresql -y
RUN echo "host all all all md5" >> /etc/postgresql/15/main/pg_hba.conf
RUN sed -i "s/#port/port/g" /etc/postgresql/15/main/postgresql.conf

RUN /etc/init.d/postgresql start

# Expose the PostgreSQL port
EXPOSE 5432

# Add VOLUMEs to allow backup of databases
VOLUME ["/var/lib/postgresql/data"]

# Set the default command to run when starting the container
CMD ["/usr/lib/postgresql/15/bin/postgres", "-D", "/var/lib/postgresql/data", "-c", "config_file=/etc/postgresql/15/main/postgresql.conf"]

--------------
FROM rockylinux:9.1

COPY startUpScript.sh /
RUN dnf clean all
RUN dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
#RUN dnf -qy module disable postgresql
RUN dnf install -y postgresql15-server
RUN /usr/pgsql-15/bin/postgresql-15-setup initdb
RUN systemctl enable postgresql-15
RUN systemctl start postgresql-15
RUN chmod 777 /startUpScript.sh
CMD ["/bin/bash","-c","/startUpScript.sh && tail -f /dev/null"]