FROM postgres:latest

RUN echo 'host all all all md5' >> /var/lib/postgresql/data/pg_hba.conf
RUN sed -i "s/#port/port/g" /usr/share/postgresql/postgresql.conf.sample

EXPOSE 5432

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["postgres"]
