apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  labels:
      app: postgres # Labels and Selectors
  spec:
    type: NodePort # Sets service type
    ports:
      - port: 5432 # Sets port to run the postgres application
        nodePort: 30432
    selector:
      app: postgres
