apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  DB_PORT: "5432"
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
