apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: postgres
spec:
  type: NodePort # Sets service type
  ports:
    - protocol: TCP
      port: 5432 # Sets port to run the postgres application
      targetPort: 5432
      nodePort: 30432
  selector:
    app: postgres
