apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          command: ["sh", "-c", "while true; do echo 'host all all 0.0.0.0/0 md5' >> /var/lib/postgresql/data/pg_hba.conf; echo 'port = 5432' >> /var/lib/postgresql/data/postgresql.conf; sleep 10; done"]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-database-auth
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-database-auth
                  key: password
            - name: POSTGRES_DB
              value: postgresdb
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
            - mountPath: /etc/authentication/postgresql/secret
              name: postgres-secret
              readOnly: true
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
        - name: postgres-secret
          secret:
            secretName: app-database-auth
